// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXmVz12P5UPwpvTX0Z-YtU5MMJ2_omFw',
    appId: '1:807836240261:web:c23def03053759abc85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    authDomain: 'fnof-stack-a31a1.firebaseapp.com',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVx6iDDBJwX-Cp_-O96SXqIbTXdDLieI',
    appId: '1:807836240261:android:7d5d383b6025fe1bc85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfED085x9IoEaXQUqv0p8bCTCqU_VEOxg',
    appId: '1:807836240261:ios:f6a580921ddf8b8ac85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
    iosBundleId: 'com.example.spaceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfED085x9IoEaXQUqv0p8bCTCqU_VEOxg',
    appId: '1:807836240261:ios:f6a580921ddf8b8ac85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
    iosBundleId: 'com.example.spaceAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsXmVz12P5UPwpvTX0Z-YtU5MMJ2_omFw',
    appId: '1:807836240261:web:013546edf0293a3ec85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    authDomain: 'fnof-stack-a31a1.firebaseapp.com',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
  );
}
