// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXmVz12P5UPwpvTX0Z-YtU5MMJ2_omFw',
    appId: '1:807836240261:web:c23def03053759abc85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    authDomain: 'fnof-stack-a31a1.firebaseapp.com',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
  );

  //for android (need?)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXmVz12P5UPwpvTX0Z-YtU5MMJ2_omFw',
    appId: '1:807836240261:android:7d5d383b6025fe1bc85cec',
    messagingSenderId: '807836240261',
    projectId: 'fnof-stack-a31a1',
    storageBucket: 'fnof-stack-a31a1.firebasestorage.app',
  );
}